print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("How much tip would you like to give? 10, 12, or 15? "))
people = int(input("How many people to split the bill?"))
bill = bill + bill * (tip / 100)
final_amount = (bill / people)
final_amount = "{:.2f}".format(final_amount)
print(f"Each person should pay: ${final_amount}")
